name: Python Quality Check (Linting Only)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install Linters
      run: |
        pip install flake8 black
        
    - name: Run Flake8
      run: |
        flake8 .

    - name: Run Black Check
      run: |
        black . --check